package org.odds.hibernate;
// Generated Mar 27, 2013 12:58:53 PM by Hibernate Tools 3.2.1.GA



/**
 * OrphanageId generated by hbm2java
 */
public class OrphanageId  implements java.io.Serializable {


     private int id;
     private int userId;

    public OrphanageId() {
    }

    public OrphanageId(int id, int userId) {
       this.id = id;
       this.userId = userId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrphanageId) ) return false;
		 OrphanageId castOther = ( OrphanageId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


