package org.odds.hibernate;
// Generated Mar 27, 2013 12:58:53 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String firstname;
     private String lastname;
     private Set orphanages = new HashSet(0);

    public User() {
    }

    public User(String firstname, String lastname, Set orphanages) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.orphanages = orphanages;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Set getOrphanages() {
        return this.orphanages;
    }
    
    public void setOrphanages(Set orphanages) {
        this.orphanages = orphanages;
    }




}


