package org.odds.hibernate.entities;
// Generated May 28, 2013 4:00:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DonationMoney generated by hbm2java
 */
public class DonationMoney  implements java.io.Serializable {


     private Integer id;
     private User user;
     private DonationCategory donationCategory;
     private String amount;
     private String status;
     private String donor;
     private String donorEmail;
     private String message;
     private Date time;
     private Integer orphanageId;

    public DonationMoney() {
    }

	
    public DonationMoney(User user, DonationCategory donationCategory, String message) {
        this.user = user;
        this.donationCategory = donationCategory;
        this.message = message;
    }
    public DonationMoney(User user, DonationCategory donationCategory, String amount, String status, String donor, String donorEmail, String message, Date time, Integer orphanageId) {
       this.user = user;
       this.donationCategory = donationCategory;
       this.amount = amount;
       this.status = status;
       this.donor = donor;
       this.donorEmail = donorEmail;
       this.message = message;
       this.time = time;
       this.orphanageId = orphanageId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public DonationCategory getDonationCategory() {
        return this.donationCategory;
    }
    
    public void setDonationCategory(DonationCategory donationCategory) {
        this.donationCategory = donationCategory;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDonor() {
        return this.donor;
    }
    
    public void setDonor(String donor) {
        this.donor = donor;
    }
    public String getDonorEmail() {
        return this.donorEmail;
    }
    
    public void setDonorEmail(String donorEmail) {
        this.donorEmail = donorEmail;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Integer getOrphanageId() {
        return this.orphanageId;
    }
    
    public void setOrphanageId(Integer orphanageId) {
        this.orphanageId = orphanageId;
    }




}


