package org.odds.hibernate.entities;
// Generated Apr 24, 2013 2:19:10 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DonationCategory generated by hbm2java
 */
public class DonationCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set donations = new HashSet(0);

    public DonationCategory() {
    }

    public DonationCategory(String name, Set donations) {
       this.name = name;
       this.donations = donations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDonations() {
        return this.donations;
    }
    
    public void setDonations(Set donations) {
        this.donations = donations;
    }




}


