package org.odds.hibernate.entities;
// Generated May 31, 2013 1:32:30 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DonationReceipt generated by hbm2java
 */
@Entity
@Table(name="donation_receipt"
    ,catalog="odds_db"
)
public class DonationReceipt  implements java.io.Serializable {


     private int id;
     private String donationId;
     private String donor;
     private String donorEmail;

    public DonationReceipt() {
    }

	
    public DonationReceipt(int id) {
        this.id = id;
    }
    public DonationReceipt(int id, String donationId, String donor, String donorEmail) {
       this.id = id;
       this.donationId = donationId;
       this.donor = donor;
       this.donorEmail = donorEmail;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="donation_id", length=45)
    public String getDonationId() {
        return this.donationId;
    }
    
    public void setDonationId(String donationId) {
        this.donationId = donationId;
    }
    
    @Column(name="donor", length=45)
    public String getDonor() {
        return this.donor;
    }
    
    public void setDonor(String donor) {
        this.donor = donor;
    }
    
    @Column(name="donor_email", length=45)
    public String getDonorEmail() {
        return this.donorEmail;
    }
    
    public void setDonorEmail(String donorEmail) {
        this.donorEmail = donorEmail;
    }




}


