package org.odds.hibernate.entities;
// Generated May 29, 2013 3:11:20 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DonationCategory generated by hbm2java
 */
@Entity
@Table(name="donation_category"
    ,catalog="odds_db"
)
public class DonationCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<DonationItem> donationItems = new HashSet<DonationItem>(0);
     private Set<DonationMoney> donationMoneies = new HashSet<DonationMoney>(0);

    public DonationCategory() {
    }

    public DonationCategory(String name, Set<DonationItem> donationItems, Set<DonationMoney> donationMoneies) {
       this.name = name;
       this.donationItems = donationItems;
       this.donationMoneies = donationMoneies;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="donationCategory")
    public Set<DonationItem> getDonationItems() {
        return this.donationItems;
    }
    
    public void setDonationItems(Set<DonationItem> donationItems) {
        this.donationItems = donationItems;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="donationCategory")
    public Set<DonationMoney> getDonationMoneies() {
        return this.donationMoneies;
    }
    
    public void setDonationMoneies(Set<DonationMoney> donationMoneies) {
        this.donationMoneies = donationMoneies;
    }




}


