package org.odds.hibernate.entities;
// Generated May 31, 2013 1:32:30 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NewsCategory generated by hbm2java
 */
@Entity
@Table(name="news_category"
    ,catalog="odds_db"
)
public class NewsCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<News> newses = new HashSet<News>(0);

    public NewsCategory() {
    }

    public NewsCategory(String name, Set<News> newses) {
       this.name = name;
       this.newses = newses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="newsCategory")
    public Set<News> getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set<News> newses) {
        this.newses = newses;
    }




}


