package org.odds.hibernate.entities;
// Generated May 28, 2013 10:11:13 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrphanageAddress generated by hbm2java
 */
@Entity
@Table(name = "orphanage_address", catalog = "odds_db")
public class OrphanageAddress implements java.io.Serializable {

    private Integer id;
    private Orphanage orphanage;
    private String settlement;
    private String district;
    private String region;

    public OrphanageAddress() {
    }

    public OrphanageAddress(Orphanage orphanage) {
        this.orphanage = orphanage;
    }

    public OrphanageAddress(Orphanage orphanage, String settlement, String district, String region) {
        this.orphanage = orphanage;
        this.settlement = settlement;
        this.district = district;
        this.region = region;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "orphanage_id", nullable = false)
    public Orphanage getOrphanage() {
        return this.orphanage;
    }

    public void setOrphanage(Orphanage orphanage) {
        this.orphanage = orphanage;
    }

    @Column(name = "settlement", length = 45)
    public String getSettlement() {
        return this.settlement;
    }

    public void setSettlement(String settlement) {
        this.settlement = settlement;
    }

    @Column(name = "district", length = 45)
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    @Column(name = "region", length = 45)
    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }
}
