package org.odds.hibernate.entities;
// Generated May 29, 2013 6:20:03 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrphanageAddress generated by hbm2java
 */
@Entity
@Table(name="orphanage_address"
    ,catalog="odds_db"
)
public class OrphanageAddress  implements java.io.Serializable {


     private Integer id;
     private Orphanage orphanage;
     private String settlement;
     private String district;
     private String region;
     private BigDecimal longitude;
     private BigDecimal latitude;

    public OrphanageAddress() {
    }

	
    public OrphanageAddress(Orphanage orphanage) {
        this.orphanage = orphanage;
    }
    public OrphanageAddress(Orphanage orphanage, String settlement, String district, String region, BigDecimal longitude, BigDecimal latitude) {
       this.orphanage = orphanage;
       this.settlement = settlement;
       this.district = district;
       this.region = region;
       this.longitude = longitude;
       this.latitude = latitude;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orphanage_id", nullable=false)
    public Orphanage getOrphanage() {
        return this.orphanage;
    }
    
    public void setOrphanage(Orphanage orphanage) {
        this.orphanage = orphanage;
    }
    
    @Column(name="settlement", length=45)
    public String getSettlement() {
        return this.settlement;
    }
    
    public void setSettlement(String settlement) {
        this.settlement = settlement;
    }
    
    @Column(name="district", length=45)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    
    @Column(name="region", length=45)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    
    @Column(name="longitude", precision=24, scale=16)
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    
    @Column(name="latitude", precision=24, scale=16)
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }




}


