package org.odds.hibernate.entities;
// Generated Apr 19, 2013 6:28:17 PM by Hibernate Tools 3.2.1.GA



/**
 * OrphanageId generated by hbm2java
 */
public class OrphanageId  implements java.io.Serializable {


     private int id;
     private int usersId;

    public OrphanageId() {
    }

    public OrphanageId(int id, int usersId) {
       this.id = id;
       this.usersId = usersId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getUsersId() {
        return this.usersId;
    }
    
    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrphanageId) ) return false;
		 OrphanageId castOther = ( OrphanageId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUsersId()==castOther.getUsersId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUsersId();
         return result;
   }   


}


