package org.odds.hibernate.entities;
// Generated May 29, 2013 3:11:20 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OrphanageContact generated by hbm2java
 */
@Entity
@Table(name="orphanage_contact"
    ,catalog="odds_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="orphanage_id") 
)
public class OrphanageContact  implements java.io.Serializable {


     private Integer id;
     private Orphanage orphanage;
     private String phone;
     private String altPhone;
     private String email;
     private String altEmail;
     private String fax;

    public OrphanageContact() {
    }

	
    public OrphanageContact(Orphanage orphanage) {
        this.orphanage = orphanage;
    }
    public OrphanageContact(Orphanage orphanage, String phone, String altPhone, String email, String altEmail, String fax) {
       this.orphanage = orphanage;
       this.phone = phone;
       this.altPhone = altPhone;
       this.email = email;
       this.altEmail = altEmail;
       this.fax = fax;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="orphanage_id", unique=true, nullable=false)
    public Orphanage getOrphanage() {
        return this.orphanage;
    }
    
    public void setOrphanage(Orphanage orphanage) {
        this.orphanage = orphanage;
    }
    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="alt_phone", length=45)
    public String getAltPhone() {
        return this.altPhone;
    }
    
    public void setAltPhone(String altPhone) {
        this.altPhone = altPhone;
    }
    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="alt_email", length=45)
    public String getAltEmail() {
        return this.altEmail;
    }
    
    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }
    
    @Column(name="fax", length=45)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }




}


