package org.odds.hibernate.entities;
// Generated Apr 19, 2013 6:11:16 PM by Hibernate Tools 3.2.1.GA



/**
 * Record generated by hbm2java
 */
public class Record  implements java.io.Serializable {


     private Integer id;
     private Boolean status;
     private String details;

    public Record() {
    }

    public Record(Boolean status, String details) {
       this.status = status;
       this.details = details;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


