package org.odds.hibernate.entities;
// Generated Apr 24, 2013 2:19:10 PM by Hibernate Tools 3.2.1.GA



/**
 * UserContact generated by hbm2java
 */
public class UserContact  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String email;
     private String altEmail;
     private String phone;
     private String altPhone;
     private String address;

    public UserContact() {
    }

	
    public UserContact(User user) {
        this.user = user;
    }
    public UserContact(User user, String email, String altEmail, String phone, String altPhone, String address) {
       this.user = user;
       this.email = email;
       this.altEmail = altEmail;
       this.phone = phone;
       this.altPhone = altPhone;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAltEmail() {
        return this.altEmail;
    }
    
    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAltPhone() {
        return this.altPhone;
    }
    
    public void setAltPhone(String altPhone) {
        this.altPhone = altPhone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


