package org.odds.hibernate.entities;
// Generated May 29, 2013 1:59:10 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserSettings generated by hbm2java
 */
@Entity
@Table(name="user_settings"
    ,catalog="odds_db"
)
public class UserSettings  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;
     private String value;

    public UserSettings() {
    }

	
    public UserSettings(User user) {
        this.user = user;
    }
    public UserSettings(User user, String name, String value) {
       this.user = user;
       this.name = name;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @Column(name="name", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="value", length=64)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


