package org.odds.hibernate.entities;
// Generated Jun 2, 2013 2:12:54 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserContact generated by hbm2java
 */
@Entity
@Table(name="user_contact"
    ,catalog="odds_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
public class UserContact  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String email;
     private String altEmail;
     private String phone;
     private String altPhone;
     private String address;

    public UserContact() {
    }

	
    public UserContact(User user) {
        this.user = user;
    }
    public UserContact(User user, String email, String altEmail, String phone, String altPhone, String address) {
       this.user = user;
       this.email = email;
       this.altEmail = altEmail;
       this.phone = phone;
       this.altPhone = altPhone;
       this.address = address;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", unique=true, nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="alt_email", length=45)
    public String getAltEmail() {
        return this.altEmail;
    }
    
    public void setAltEmail(String altEmail) {
        this.altEmail = altEmail;
    }
    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    @Column(name="alt_phone", length=45)
    public String getAltPhone() {
        return this.altPhone;
    }
    
    public void setAltPhone(String altPhone) {
        this.altPhone = altPhone;
    }
    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


