package org.odds.hibernate.entities;
// Generated May 6, 2013 2:07:43 PM by Hibernate Tools 3.2.1.GA



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private int id;
     private User user;
     private String authority;

    public UserRole() {
    }

    public UserRole(int id, User user, String authority) {
       this.id = id;
       this.user = user;
       this.authority = authority;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(String authority) {
        this.authority = authority;
    }




}


