package org.odds.hibernate.entities;
// Generated May 28, 2013 4:00:36 PM by Hibernate Tools 3.2.1.GA



/**
 * UserSettings generated by hbm2java
 */
public class UserSettings  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;
     private String value;

    public UserSettings() {
    }

	
    public UserSettings(User user) {
        this.user = user;
    }
    public UserSettings(User user, String name, String value) {
       this.user = user;
       this.name = name;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


